### ISSUE TITLE
Add SonarQube scan

### ISSUE THREAD

**Issue by maxadamo** [Uninett/Argus-frontend#358]
### Proposal

*Scan your code with Géant SonarQube*

### Desired solution

we kindly ask you to add the following task to your existing GitHub Actions:

```yaml
name: SonarQube CI
on: push
jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@v1.1.0
      with:
        host: ${{ secrets.SONARQUBE_HOST }}
        login: ${{ secrets.SONARQUBE_TOKEN }}
```

`SONARQUBE_HOST`: it can be a secret or you can hard-code it the CI. I's value is: `sonarqube.software.geant.org`
`SONARQUBE_TOKEN`: Please contact me for the token.
